IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'visual')
BEGIN
    EXEC('CREATE DATABASE [visual]')
END
GO
USE [visual];
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'login')
BEGIN
    CREATE TABLE [login] (
        [id] INT IDENTITY(1,1) PRIMARY KEY,
        [username] VARCHAR(100),
        [password] VARCHAR(255),
        [last_login] DATETIME,
        [is_active] VARCHAR(10)
    );
END

-- 1. USERS TABLOSU
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'users')
BEGIN
    CREATE TABLE [users] (
        [id] INT IDENTITY(1,1) PRIMARY KEY,
        [first_name] VARCHAR(100), 
        [last_name] VARCHAR(100),  
        [e_mail] VARCHAR(100),
        [phone_number] VARCHAR(100),
        [city] VARCHAR(100)
    );
END

-- 2. ITEMS TABLOSU
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'items')
BEGIN
    CREATE TABLE [items] (
        [id] INT IDENTITY(1,1) PRIMARY KEY,
        [name] VARCHAR(100),
        [properties] VARCHAR(5000), 
        [prize] FLOAT,            
        [is_active] VARCHAR(10)
    );
END

-- 3. ORDERS TABLOSU
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'orders')
BEGIN
    CREATE TABLE [orders] (
        [id] INT IDENTITY(1,1) PRIMARY KEY,
        [user_id] INT,
        [item_id] INT,
        [item_list] VARCHAR(1000),
        [prize] FLOAT,
        [status] VARCHAR(100),
    );
END


INSERT INTO login (username, password, last_login, is_active)
VALUES
('1', 'portakal', NULL, 'active'),
('1mireliamidsal', 'Yoed!61@', NULL, 'active'),
('1mirelyamıolurla', 'Arafilboylu61e61', NULL, 'active'),
('abdusselam', 'konyaspor', NULL, 'active'),
('abul', 'ensar61', NULL, 'active'),
('ahmet', 'ata33', NULL, 'active'),
('Animagus', 'animagus123', NULL, 'active'),
('Ardentia', 'testfos', NULL, 'active'),
('Argus', 'argus123', NULL, 'active'),
('Aslan_05', 'frnndmslr', NULL, 'active'),
('atlıkarınca', 'Arafilboylu61e61', NULL, 'active'),
('Attila Semiz', 'hun453', NULL, 'active'),
('Aybüke Çotan', 'aybke2946', NULL, 'active'),
('Ayhan Yapraklı', 'ayhanbaba31', NULL, 'active'),
('bayanTokyo', 'ıloveRio_', NULL, 'active'),
('berkay', 'R#9mP!gZ2wQk*4', NULL, 'active'),
('beyaz', 'beyaz1', NULL, 'active'),
('beyto', 'anubis12', NULL, 'active'),
('beyza', 'jT5@yF8c7bLp&D', NULL, 'active'),
('biri1', 'jT5@yF8c7bLp&D', NULL, 'active'),
('biri2', 'jT5@yF8c7bLp&D', NULL, 'active'),
('bordo', 'bordo1', NULL, 'active'),
('Bulbasaur', 'bulbasaur123', NULL, 'active'),
('Cahit Kosovalı', 'cht936754', NULL, 'active'),
('can', 'doom55', NULL, 'active'),
('Cangoooo', 'cangoo121421', NULL, 'active'),
('Capon', 'hans22', NULL, 'active'),
('captain', '5123', NULL, 'active'),
('cat1', 'yasmama16', NULL, 'active'),
('cat10', 'yasmama25', NULL, 'active'),
('cat2', 'yasmama17', NULL, 'active'),
('cat3', 'yasmama18', NULL, 'active'),
('cat4', 'yasmama20', NULL, 'active'),
('cat6', 'yasmama21', NULL, 'active'),
('cat7', 'yasmama22', NULL, 'active'),
('cat8', 'yasmama23', NULL, 'active'),
('cat9', 'yasmama24', NULL, 'active'),
('Charmander', 'charmander123', NULL, 'active'),
('cheribum', 'cherceh.2131', NULL, 'active'),
('Cocacolastic', 'Melikşah623', NULL, 'active'),
('covenant', 'portakal', NULL, 'active'),
('Cristiano_7', 'Goat_7', NULL, 'active'),
('Dante', 'vergil77', NULL, 'active'),
('DarkMaw', 'ata33', NULL, 'active'),
('Diagon', 'diagon123', NULL, 'active'),
('Dida', '1234556', NULL, 'active'),
('dijitalportakal', '12345678@#', NULL, 'active'),
('Doom Slayer', 'doom55', NULL, 'active'),
('driver', '8971', NULL, 'active'),
('ederson', 'gençlerbirliği', NULL, 'active'),
('Edo', 'portakal', NULL, 'active'),
('edo1', 'portakal', NULL, 'active'),
('Elandria', 'codingcode', NULL, 'active'),
('Elif Gülfidan', 'glfdn9267', NULL, 'active'),
('emir', 'jT5@yF8c7bLp&D', NULL, 'active'),
('enes', 'şampiyonfener', NULL, 'active'),
('Enes Kalaycı', 'Kklaycı55', NULL, 'active'),
('equisar', 'ensar61', NULL, 'active'),
('Erkan Saral', '22erkan33', NULL, 'active'),
('etçilbitki', 'Arafilboylu61e61', NULL, 'active'),
('eyl', 'ruhi123', NULL, 'active'),
('eylul', 'ruhi123', NULL, 'active'),
('Fadime Güler', 'fadime1461', NULL, 'active'),
('Fatihsultantedesco', '14531453(*', NULL, 'active'),
('gabriel', 'gabgab5321', NULL, 'active'),
('Gastromel', 'melih44', NULL, 'active'),
('Glype', 'Enes117', NULL, 'active'),
('gri', 'gri1', NULL, 'active'),
('hakan', 'erzurumspor', NULL, 'active'),
('Hanmetin', 'metinmetin', NULL, 'active'),
('herhangibiri1', 'herhangişifre1', NULL, 'active'),
('herhangibiri2', 'herhangişifre2', NULL, 'active'),
('herhangibiri3', 'herhangişifre3', NULL, 'active'),
('herhangibiri4', 'herhangişifre4', NULL, 'active'),
('herhangibiri5', 'herhangişifre5', NULL, 'active'),
('herhangibiri6', 'herhangişifre6', NULL, 'active'),
('Hz.Yusuf', 'kuyu1234', NULL, 'active'),
('İbrahim Saltuk', 'brhm234', NULL, 'active'),
('ieyll', 'ruhi123', NULL, 'active'),
('ireliaoynarım0', 'YD5e$L9tQ', NULL, 'active'),
('ireliaoynarım2', 'R4t!9BxQ', NULL, 'active'),
('ireliaoynarım3', 'K8m$Q2Lp', NULL, 'active'),
('ireliaoynarım4', 'S7d#V3nR', NULL, 'active'),
('ireliaoynarım5', 'F9h@Q6wT', NULL, 'active'),
('ireliaoynarım6', 'Z2p%M8kH', NULL, 'active'),
('ireliaoynarım7', 'T6q!P4sX', NULL, 'active'),
('ireliaoynarım8', 'B3v@N7qL', NULL, 'active'),
('ireliaoynarım9', 'H8s#K2mW', NULL, 'active'),
('irelyaçokkötü', 'Arafilboylu61e61', NULL, 'active'),
('ismail', 'denizlispor', NULL, 'active'),
('Jigglypuff', 'jigglypuff123', NULL, 'active'),
('Juargos', 'Haluk214', NULL, 'active'),
('kabu', 'hans22', NULL, 'active'),
('kaçmayanfare', 'Arafilboylu61e61', NULL, 'active'),
('Kanarya_07', 'fener_1907', NULL, 'active'),
('kapanmayankapı3', 'Arafilboylu61e61', NULL, 'active'),
('Kaplan_61', '61TS1967', NULL, 'active'),
('KARA BOGA', 'portakal', NULL, 'active'),
('Karga_51', 'Krga_123', NULL, 'active'),
('Kartal_1903', 'QR71903', NULL, 'active'),
('kıto', 'vergil77', NULL, 'active'),
('kirmizi', 'kirmizi1', NULL, 'active'),
('kirpi1', 'yılan1', NULL, 'active'),
('kirpi10', 'yılan10', NULL, 'active'),
('kirpi2', 'yılan2', NULL, 'active'),
('kirpi3', 'yılan3', NULL, 'active'),
('kirpi4', 'yılan4', NULL, 'active'),
('kirpi5', 'yılan5', NULL, 'active'),
('kirpi6', 'yılan6', NULL, 'active'),
('kirpi7', 'yılan7', NULL, 'active'),
('kirpi8', 'yılan8', NULL, 'active'),
('kirpi9', 'yılan9', NULL, 'active'),
('kln4', 'ruhi123', NULL, 'active'),
('kln5', 'ruhi123', NULL, 'active'),
('kln6', 'ruhi123', NULL, 'active'),
('kln7', 'ruhi123', NULL, 'active'),
('korkusuzkarınca', 'Arafilboylu61e61', NULL, 'active'),
('kullanici1', 'ruhi123', NULL, 'active'),
('kullanici2', 'ruhi123', NULL, 'active'),
('kullanici3', 'ruhi123', NULL, 'active'),
('Kuzgun_52', 'KzGn?52', NULL, 'active'),
('Kyrenis', 'installation', NULL, 'active'),
('LITEON', 'lit125ı320', NULL, 'active'),
('Limon', 'limon2131', NULL, 'active'),
('Lionel_10', 'Barca_10', NULL, 'active'),
('luna', '8971', NULL, 'active'),
('Lunaris', 'securetest', NULL, 'active'),
('Luriyy', 'Ayberk102', NULL, 'active'),
('lYETOl', 'Yiğit206', NULL, 'active'),
('mamul', 'emirhan11', NULL, 'active'),
('mavi', 'mavi1', NULL, 'active'),
('mehmet', 'metinmetin', NULL, 'active'),
('Mehmet Durmaz', 'mmt9247', NULL, 'active'),
('mor', 'mor1', NULL, 'active'),
('muzaffer', 'ankaragücü', NULL, 'active'),
('neopolitikçağ', 'Arafilboylu61e61', NULL, 'active'),
('night', '5432', NULL, 'active'),
('nova', '5556', NULL, 'active'),
('nur', 'jT5@yF8c7bLp&D', NULL, 'active'),
('oli', 'Arafilboylu61e61', NULL, 'active'),
('Onuachu', 'Arafilboylu61e61', NULL, 'active'),
('Onur Karahanlı', 'onrkrhn55', NULL, 'active'),
('Orvion', 'challenging', NULL, 'active'),
('Pandesteron', 'Umut425', NULL, 'active'),
('Pankav', 'Ahmet636', NULL, 'active'),
('pazo', 'Arafilboylu61e61', NULL, 'active'),
('pembe', 'pembe1', NULL, 'active'),
('Pikachu', 'pikachu123', NULL, 'active'),
('pixel', '6123', NULL, 'active'),
('polat', 'melih44', NULL, 'active'),
('Preiros', 'preiros123', NULL, 'active'),
('R_K_in_the_house', 'RmzKmlk', NULL, 'active'),
('Raviel', 'superscret', NULL, 'active'),
('Reborn', 'emirhan11', NULL, 'active'),
('Sabri Tütüncüoğlu', 'tt48654', NULL, 'active'),
('salı', 'Arafilboylu61e61', NULL, 'active'),
('Salih Kasva', 'Kasva55', NULL, 'active'),
('samurai', '1100', NULL, 'active'),
('sarısınsızdünya:(', 'Arafilboylu61e61', NULL, 'active'),
('selim', 'jT5@yF887bLp&f', NULL, 'active'),
('Selim Sarı', 'jks4738', NULL, 'active'),
('SentryAgain', 'Ozan528', NULL, 'active'),
('Sezar', '_venividivici_', NULL, 'active'),
('shadow', '3451', NULL, 'active'),
('Shephard', 'anubis12', NULL, 'active'),
('siyah', 'siyah1', NULL, 'active'),
('ss13 lover', 'limon123', NULL, 'active'),
('StayZen', 'Berkay729', NULL, 'active'),
('steafan', '1234', NULL, 'active'),
('Stewar1', 'Eren277', NULL, 'active'),
('Subutay', 'mızraklıbirmoğol_', NULL, 'active'),
('Sulko', 'portakal', NULL, 'active'),
('Şevşenkoo61', '14616161', NULL, 'active'),
('talisca', 'adanaspor', NULL, 'active'),
('tedesco', 'beşiktaş', NULL, 'active'),
('Thalena', 'demo$dg@rasd', NULL, 'active'),
('tilki1', 'surungen1', NULL, 'active'),
('tilki10', 'surungen10', NULL, 'active'),
('tilki2', 'surungen2', NULL, 'active'),
('tilki3', 'surungen3', NULL, 'active'),
('tilki4', 'surungen4', NULL, 'active'),
('tilki5', 'surungen5', NULL, 'active'),
('tilki6', 'surungen6', NULL, 'active'),
('tilki7', 'surungen7', NULL, 'active'),
('tilki8', 'surungen8', NULL, 'active'),
('tilki9', 'surungen9', NULL, 'active'),
('turbo', '9861', NULL, 'active'),
('turuncu', 'turuncu1 ', NULL, 'active'),
('Ugg''Nug', 'complexmoney', NULL, 'active'),
('Umbreon', 'umbreon123', NULL, 'active'),
('Velora', 'administrator', NULL, 'active'),
('vero', 'alicia44', NULL, 'active'),
('Verso', 'alicia44', NULL, 'active'),
('Vlademir', 'Iloveputin_', NULL, 'active'),
('wei Jinhang', 'portakal', NULL, 'active'),
('Xin', 'portakal', NULL, 'active'),
('Xionate', 'Furkan701', NULL, 'active'),
('Yakup Okkali', 'parola61', NULL, 'active'),
('Yasin Oktay', 'biryudumzehir', NULL, 'active'),
('yesil', 'yesil1', NULL, 'active'),
('yusuf', 'trabzonspor', NULL, 'active'),
('yüzemeyenbalik', 'Arafilboylu61e61', NULL, 'active'),
('Zümrüdüanka_32', 'Zmrdnk!32', NULL, 'active'),
('Zyphor', 'password123', NULL, 'active');

GO